ALTER TABLE public.inspections 
ADD COLUMN IF NOT EXISTS sent_by TEXT,
ADD COLUMN IF NOT EXISTS picker_name TEXT,
ADD COLUMN IF NOT EXISTS picker_phone TEXT,
ADD COLUMN IF NOT EXISTS picker_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS picker_signature TEXT;
